{{- $highAvailability := gt (int .Values.keycloak.replicas) 1 -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "keycloak.fullname" . }}
  annotations:
    checksum/config-sh: {{ include (print .Template.BasePath "/configmap-sh.yaml") . | sha256sum }}
    checksum/config-startup: {{ include (print .Template.BasePath "/configmap-startup.yaml") . | sha256sum }}
  labels:
    app: {{ template "keycloak.name" . }}
    chart: {{ template "keycloak.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  selector:
    matchLabels:
      app: {{ template "keycloak.name" . }}
      release: "{{ .Release.Name }}"
  replicas: {{ .Values.keycloak.replicas }}
  serviceName: {{ template "keycloak.fullname" . }}-headless
  podManagementPolicy: Parallel
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ template "keycloak.name" . }}
        release: "{{ .Release.Name }}"
      {{- with .Values.keycloak.podLabels }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.keycloak.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.keycloak.hostAliases }}
      hostAliases:
      {{ toYaml . | indent 8 }}
      {{- end }}
      {{- if (semverCompare ">=1.13-0" .Capabilities.KubeVersion.GitVersion) }}
      enableServiceLinks: {{ .Values.keycloak.enableServiceLinks }}
      {{- end }}
      serviceAccountName: {{ template "keycloak.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.keycloak.securityContext | nindent 8 }}
    {{- with .Values.keycloak.image.pullSecrets }}
      imagePullSecrets:
      {{- range . }}
        - name: {{ . }}
      {{- end }}
    {{- end }}
    {{- if or .Values.keycloak.persistence.deployPostgres .Values.keycloak.extraInitContainers }}
      initContainers:
      {{- if .Values.keycloak.persistence.deployPostgres }}
        - name: wait-for-postgresql
          image: "{{ .Values.init.image.repository }}:{{ .Values.init.image.tag }}"
          imagePullPolicy: {{ .Values.init.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.keycloak.containerSecurityContext | nindent 12 -}}
          command:
            - sh
            - -c
            - |
              until printf "." && nc -z -w 2 {{ template "keycloak.postgresql.fullname" . }} {{ .Values.postgresql.service.port }}; do
                  sleep 2;
              done;

              echo 'PostgreSQL OK ✓'
      {{- end }}
      {{- with .Values.keycloak.extraInitContainers }}
        {{- tpl . $ | nindent 8 }}
      {{- end }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.keycloak.image.repository }}:{{ .Values.keycloak.image.tag }}"
          imagePullPolicy: {{ .Values.keycloak.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.keycloak.containerSecurityContext | nindent 12 -}}
          command:
            - /scripts/keycloak.sh
          {{- with .Values.keycloak.lifecycleHooks }}
          lifecycle:
            {{- tpl . $ | nindent 12 }}
          {{- end }}
          env:
          {{- if or .Release.IsInstall .Values.keycloak.sidecar.realms.enabled }}
            - name: KEYCLOAK_USER
              value: {{ .Values.keycloak.username }}
            - name: KEYCLOAK_PASSWORD
              valueFrom:
                secretKeyRef:
                {{- if .Values.keycloak.existingSecret }}
                  name: {{ .Values.keycloak.existingSecret }}
                {{- else }}
                  name: {{ template "keycloak.fullname" . }}-http
                {{- end }}
                  key: {{ .Values.keycloak.existingSecretKey }}
          {{- end }}
          {{- if .Values.keycloak.sidecar.realms.enabled }}
            - name: REALMS_FOLDER
              value: "{{ .Values.keycloak.sidecar.realms.folder }}{{- with .Values.keycloak.sidecar.realms.defaultFolderName }}/{{ . }}{{- end }}"
            - name: REALM_UPDATER_INTERVAL
              value: "{{ .Values.keycloak.sidecar.realms.interval }}"
          {{- end }}
          {{- if $highAvailability }}
            - name: JGROUPS_DISCOVERY_PROTOCOL
              value: "dns.DNS_PING"
            - name: JGROUPS_DISCOVERY_PROPERTIES
              value: "dns_query={{ template "keycloak.fullname" . }}-headless.{{ .Release.Namespace }}.svc.{{ .Values.clusterDomain }}"
          {{- end }}
            {{- include "keycloak.dbEnvVars" . | nindent 12 }}
          {{- with .Values.keycloak.extraEnv }}
            {{- tpl . $ | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: sh
              mountPath: /scripts
            - name: startup
              mountPath: /opt/jboss/startup-scripts
          {{- if .Values.keycloak.sidecar.realms.enabled }}
            - name: sc-realms-volume
              mountPath: {{ .Values.keycloak.sidecar.realms.folder | quote }}
          {{- end }}
          {{- with .Values.keycloak.extraVolumeMounts }}
            {{- tpl . $ | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          {{- if $highAvailability }}
            - name: jgroups
              containerPort: 7600
              protocol: TCP
          {{- end }}
          {{- with .Values.keycloak.extraPorts }}
            {{- tpl . $ | nindent 12 }}
          {{- end }}
          livenessProbe:
            httpGet:
              path: {{ if ne .Values.keycloak.basepath "" }}/{{ .Values.keycloak.basepath }}{{ end }}/
              port: http
            initialDelaySeconds: {{ .Values.keycloak.livenessProbe.initialDelaySeconds }}
            timeoutSeconds: {{ .Values.keycloak.livenessProbe.timeoutSeconds }}
          readinessProbe:
            httpGet:
              path: {{ if ne .Values.keycloak.basepath "" }}/{{ .Values.keycloak.basepath }}{{ end }}/realms/master
              port: http
            initialDelaySeconds: {{ .Values.keycloak.readinessProbe.initialDelaySeconds }}
            timeoutSeconds: {{ .Values.keycloak.readinessProbe.timeoutSeconds }}
          resources:
            {{- toYaml .Values.keycloak.resources | nindent 12 }}
      {{- if .Values.keycloak.sidecar.realms.enabled }}
        - name: {{ .Chart.Name }}-sc-realms
          image: "{{ .Values.keycloak.sidecar.image.repository }}:{{ .Values.keycloak.sidecar.image.tag }}"
          imagePullPolicy: {{ .Values.keycloak.sidecar.image.pullPolicy }}
          env:
            - name: LABEL
              value: "{{ .Values.keycloak.sidecar.realms.label }}"
            - name: FOLDER
              value: "{{ .Values.keycloak.sidecar.realms.folder }}{{- with .Values.keycloak.sidecar.realms.defaultFolderName }}/{{ . }}{{- end }}"
          {{- if .Values.keycloak.sidecar.realms.searchNamespace }}
            - name: NAMESPACE
              value: "{{ .Values.keycloak.sidecar.realms.searchNamespace }}"
          {{- end }}
          resources:
            {{- toYaml .Values.keycloak.sidecar.resources | nindent 12 }}
          volumeMounts:
            - name: sc-realms-volume
              mountPath: {{ .Values.keycloak.sidecar.realms.folder | quote }}
      {{- end }}
      {{- with .Values.keycloak.extraContainers }}
        {{- tpl . $ | nindent 8 }}
      {{- end }}
      {{- with .Values.keycloak.affinity }}
      affinity:
        {{- tpl . $ | nindent 8 }}
      {{- end }}
      {{- with .Values.keycloak.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.keycloak.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.keycloak.priorityClassName }}
      priorityClassName: {{ . }}
      {{- end }}
      terminationGracePeriodSeconds: 60
      volumes:
        - name: sh
          configMap:
            name: {{ template "keycloak.fullname" . }}-sh
            defaultMode: 0555
        - name: startup
          configMap:
            name: {{ template "keycloak.fullname" . }}-startup
            defaultMode: 0555
      {{- if .Values.keycloak.sidecar.realms.enabled }}
        - name: sc-realms-volume
          emptyDir: {}
      {{- end }}
      {{- with .Values.keycloak.extraVolumes }}
        {{- tpl . $ | nindent 8 }}
      {{- end }}
